name: .NET Core

# SPDX-FileCopyrightText: Copyright (c) 2009-2020 TRUMPF Laser GmbH, authors: C-Labs
# SPDX-License-Identifier: CC0-1.0

on:
  push:
    branches: [ master ]
    tags: [ '[1-9]+.[0-9]+.[0-9]+*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET 6
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: 6.0.*
        config-file: .\nuget.config